DROP PROCEDURE IF EXISTS errorproc;
DELIMITER $$
CREATE PROCEDURE errorproc()
BEGIN
DECLARE CONTINUE HANDLER FOR 1146 SELECT '테이블이 없어요 ㅠㅠ' AS '메세지';
SELECT * FROM noTable;
END $$
DELIMITER ;
CALL errorproc();

DROP PROCEDURE IF EXISTS errorproc2;
DELIMITER $$
CREATE PROCEDURE errorproc2()
BEGIN
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
BEGIN
SHOW ERRORS;
SELECT '에러가 발생했네요. 작업은 취소시켰습니다!' AS '메세지';
ROLLBACK;
END;
INSERT INTO usertbl VALUES('LSG','이상구',1998,'서울',NULL,NULL,170,CURRENT_DATE());
END $$
DELIMITER ;
CALL errorproc2();