DROP TABLE IF EXISTS buyTBL,userTBL;
CREATE TABLE userTBL(userID CHAR(8) NOT NULL PRIMARY KEY,
name VARCHAR(10) NOT NULL,
birthYear INT NOT NULL);
CREATE TABLE buyTBL(num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
userID CHAR(8) NOT NULL,
prodName CHAR(6) NOT NULL,
FOREIGN KEY(userID)REFERENCES userTBL(userID));

DROP TABLE IF EXISTS buyTBL;
CREATE TABLE buyTBL(num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
userID CHAR(8) NOT NULL,
prodName CHAR(6) NOT NULL,
CONSTRAINT FK_userTBL_buyTBL FOREIGN KEY(userID)REFERENCES userTBL(userID));

DROP TABLE IF EXISTS buyTBL;
CREATE TABLE buyTBL(num INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
userID CHAR(8) NOT NULL,
prodName CHAR(6) NOT NULL);
ALTER TABLE buyTBL
ADD CONSTRAINT FK_userTBL_buyTBL
FOREIGN KEY (userID)
REFERENCES userTBL(userID);

ALTER TABLE buytbl
DROP FOREIGN KEY FK_userTBL_buyTBL;
ALTER TABLE buytbl
ADD CONSTRAINT FK_userTBL_buyTBL
FOREIGN KEY (userID)
REFERENCES usertbl(userID)
ON UPDATE CASCADE;
