USE sqldb;
CREATE TABLE testTbl2(id int AUTO_INCREMENT PRIMARY KEY ,userName char(3),age int);
INSERT INTO testTbl2 VALUES(NULL,'지민',25);
INSERT INTO testTbl2 VALUES(NULL,'유나',22);
INSERT INTO testTbl2 VALUES(NULL,'유정',21);
SELECT * FROM testTbl2

ALTER TABLE testTbl2 AUTO_INCREMENT=100;
INSERT INTO testTbl2 VALUES(NULL,'찬미',23);
SELECT * FROM testTbl2